package com.example.demo.SmartDashboard.Model;

public enum TrailerType {
    GESLOTEN_KAST, OPEN, HUIF, KRAANWAGEN, DIEPLADER, FRIGO, CONTAINER, AANHANGWAGEN, PLATEAU, ARBOR, VAN_LEEUWEN, CNT_CHASSIS,
    HUIF_MEGA, WALKING_FLOOR, TESTAS, KIPPER
}
